PRODUCT_PROPERTY_OVERRIDES +=  \
    persist.radio.multisim.config=ssss \
    persist.vendor.radio.5g_mode_pref=1 \
    ro.telephony.default_network=32,22 \
    ro.vendor.boot.project_name=19861 \
    ro.boot.project_name=19861 \
    rild.libpath=/vendor/lib64/libril-qc-hal-qmi.so \
    vendor.boot.verifiedbootstate=orange \
    persist.vendor.radio.default_sa_enabled=1
